outputdir: outputs/energy_pixel_interaction/impacts-blueghost/median_OTHERIND_electricity_TINV_clim_GMFD
levels-weighting: population * social/baselines/energy/REMINDMAgPIE1730_rcp85_Prices_COMPILE.dta:country:year:electricitycompile_price
aggregate-weighting-numerator: population * social/baselines/energy/REMINDMAgPIE1730_rcp85_Prices_COMPILE.dta:country:year:electricitycompile_price
aggregate-weighting-denominator: population
infix: REMINDMAgPIE1730_rcp85pc
rcp: rcp85
only-farmers: ['', 'histclim']
