module: /global/scratch/tbearpark/repos/energy-code-release-2020/projection_inputs/configs/GMFD/TINV_clim_income_spline/break2_Exclude/semi-parametric/Projection_Configs/laika/model/hddcddspline_OTHERIND_electricity.yml
mode: median
outputdir: /global/scratch/tbearpark/outputs/energy/impacts-blueghost/median_OTHERIND_electricity_TINV_clim_income_spline_GMFD_dm
do_farmers: true
do_historical: true
deltamethod: yes
only-ssp: SSP3
econcovar:
   class: mean
   length: 15
climcovar:
   class: mean
   length: 15
loggdppc-delta: 9.087
timeout: 30
