outputdir: outputs/energy/impacts-blueghost/median_OTHERIND_electricity_TINV_clim_income_spline_GMFD
levels-weighting: population * social/baselines/energy/REMIND17_rcp85_Prices_COMPILE.dta:country:year:electricitycompile_price
aggregate-weighting-numerator: population * social/baselines/energy/REMIND17_rcp85_Prices_COMPILE.dta:country:year:electricitycompile_price
aggregate-weighting-denominator: population
infix: REMIND17_rcp85pc
rcp: rcp85
