outputdir: outputs/energy_pixel_interaction/impacts-blueghost
levels-weighting: population * social/baselines/energy/REMIND17CEMICS_rcp45_Prices_COMPILE.dta:country:year:other_energycompile_price
targetdir: impacts-blueghost/single-OTHERIND_other_energy_FD_FGLS_719_Exclude_all-issues_break2_semi-parametric_TINV_clim_GMFD_dm/rcp45/CCSM4/high/SSP3
aggregate-weighting-numerator: population * social/baselines/energy/REMIND17CEMICS_rcp45_Prices_COMPILE.dta:country:year:other_energycompile_price
aggregate-weighting-denominator: population
infix: REMIND17CEMICS_rcp45pc
rcp: rcp45
