results-root: /shares/gcp/outputs/energy/impacts-blueghost/median_OTHERIND_electricity_TINV_clim_income_spline_lininter_GMFD
deltamethod: /shares/gcp/outputs/energy/impacts-blueghost/median_OTHERIND_electricity_TINV_clim_income_spline_lininter_GMFD_dm
output-dir: /shares/gcp/social/parameters/energy/extraction/multi-models/rationalized_code/break2_Exclude_all-issues_semi-parametric/TINV_clim_income_spline_lininter_GMFD/median_OTHERIND_electricity_TINV_clim_income_spline_lininter_GMFD
file-organize: [ssp, rcp]
do-montecarlo: no
only-rcp: null
only-models: all
only-iam: null
column: rebased
evalqvals: ['mean', .5, 0.05, 0.95, 0.10, 0.90, 0.75, 0.25]
output-format: edfcsv
