results-root:
  FD_FGLS_inter_OTHERIND_other_energy_TINV_clim_lininter_half.*: impacts-blueghost/median_OTHERIND_other_energy_TINV_clim_lininter_half_GMFD_dm
  FD_FGLS_inter_OTHERIND_electricity_TINV_clim_lininter_half.*: impacts-blueghost/median_OTHERIND_electricity_TINV_clim_lininter_half_GMFD_dm
multiimpact_vcv: /Users/ruixueli/Downloads/repos//energy-code-release-2020/projection_inputs/csvv/TINV_clim_lininter_half/FD_FGLS_inter_OTHERIND_TINV_clim_lininter_half.csv
output-dir: //Users/ruixueli/Downloads/energy_data_release/OUTPUT/extracted_projection_data/TINV_clim_lininter_half_GMFD/total_energy
file-organize: [ssp, rcp]
do-montecarlo: no
only-models: all
only-iam: null
deltamethod: true
column: rebased
evalqvals: ['mean', 0.05, 0.95]
output-format: edfcsv
