timerate: year
climate: [ tas, tas-poly-2, tas-cdd-20, tas-cdd-20-poly-2, tas-hdd-20, tas-hdd-20-poly-2 ]
models:
  - csvvs: "/shares/gcp/social/parameters/energy/incspline0719/GMFD/TINV_clim_income_spline_lininter_double/FD_FGLS_inter_climGMFD_Exclude_all-issues_break2_semi-parametric_poly2_OTHERIND_electricity_TINV_clim_income_spline_lininter_double.csvv"
    covariates:
      - incbin: [ -inf, 7.246, 7.713, 8.136, 8.475, 8.776, 9.087, 9.385, 9.783, 10.198, inf ]
      - year*incbin: [ -inf, 7.246, 7.713, 8.136, 8.475, 8.776, 9.087, 9.385, 9.783, 10.198, inf ]
      - climtas-cdd-20
      - climtas-hdd-20
      - climtas-cdd-20*incbin: [ -inf, 7.246, 7.713, 8.136, 8.475, 8.776, 9.087, 9.385, 9.783, 10.198, inf ]
      - climtas-hdd-20*incbin: [ -inf, 7.246, 7.713, 8.136, 8.475, 8.776, 9.087, 9.385, 9.783, 10.198, inf ]
      - loggdppc-shifted*incbin: [ -inf, 7.246, 7.713, 8.136, 8.475, 8.776, 9.087, 9.385, 9.783, 10.198, inf ]
      - loggdppc-shifted*year*incbin: [ -inf, 7.246, 7.713, 8.136, 8.475, 8.776, 9.087, 9.385, 9.783, 10.198, inf ]
    clipping: false
    description: Change in energy usage driven by a single day's mean temperature
    depenunit: kWh/pc
    specifications:
      tas:
        description: Uninteracted term.
        indepunit: C
        functionalform: polynomial
        variable: tas
      hdd-20:
        description: Below 20C days.
        indepunit: C
        functionalform: polynomial
        variable: tas-hdd-20
      cdd-20:
        description: Above 20C days.
        indepunit: C
        functionalform: polynomial
        variable: tas-cdd-20
    calculation:
      - Sum:
        - YearlyApply:
            model: tas
        - YearlyApply:
            model: hdd-20
        - YearlyApply:
            model: cdd-20
        - unshift: false
      - Rebase:
          unshift: false
