outputdir: outputs/energy/impacts-blueghost
levels-weighting: population * social/baselines/energy/WITCHGLOBIOM42_rcp45_Prices_COMPILE.dta:country:year:electricitycompile_price
targetdir: /shares/gcp/outputs/energy/impacts-blueghost/single-OTHERIND_electricity_FD_FGLS_719_Exclude_all-issues_break2_semi-parametric_TINV_clim_income_spline_GMFD_dm/rcp45/CCSM4/high/SSP3
aggregate-weighting-numerator: population * social/baselines/energy/WITCHGLOBIOM42_rcp45_Prices_COMPILE.dta:country:year:electricitycompile_price
aggregate-weighting-denominator: population
infix: WITCHGLOBIOM42_rcp45pc
rcp: rcp45
