results-root:
  FD_FGLS_inter_climGMFD_Exclude_all-issues_break2_semi-parametric_poly2_OTHERIND_other_energy_TINV_clim_income_spline.*: /shares/gcp/outputs/energy/impacts-blueghost/median_OTHERIND_other_energy_TINV_clim_income_spline_GMFD_dm
  FD_FGLS_inter_climGMFD_Exclude_all-issues_break2_semi-parametric_poly2_OTHERIND_electricity_TINV_clim_income_spline.*: /shares/gcp/outputs/energy/impacts-blueghost/median_OTHERIND_electricity_TINV_clim_income_spline_GMFD_dm
multiimpact_vcv: /shares/gcp/social/parameters/energy/incspline0719/GMFD/TINV_clim_income_spline/FD_FGLS_inter_climGMFD_Exclude_all-issues_break2_semi-parametric_poly2_OTHERIND_TINV_clim_income_spline-fixed.csv
output-dir: /shares/gcp/social/parameters/energy/extraction/multi-models/rationalized_code/break2_Exclude_all-issues_semi-parametric/TINV_clim_income_spline_GMFD/total_energy/REMINDMAgPIE1730_rcp45pc
file-organize: [ssp, region]
do-montecarlo: no
only-models: all
only-iam: null
deltamethod: true
column: rebased
output-format: valuescsv
