outputdir: outputs/energy_pixel_interaction/impacts-blueghost/median_OTHERIND_electricity_TINV_clim_GMFD
levels-weighting: population * social/baselines/energy/IEA_Price_FIN_Clean_gr03_GLOBAL_COMPILE.dta:country:year:electricitycompile_price
aggregate-weighting-numerator: population * social/baselines/energy/IEA_Price_FIN_Clean_gr03_GLOBAL_COMPILE.dta:country:year:electricitycompile_price
aggregate-weighting-denominator: sum-to-1
infix: price03
only-farmers: ['', 'histclim']
