results-root:
  FD_FGLS_inter_OTHERIND_other_energy_TINV_clim_lininter.*: impacts-blueghost/median_OTHERIND_other_energy_TINV_clim_lininter_GMFD
  FD_FGLS_inter_OTHERIND_electricity_TINV_clim_lininter.*: impacts-blueghost/median_OTHERIND_electricity_TINV_clim_lininter_GMFD
output-dir: //Users/ruixueli/Downloads/energy_data_release/OUTPUT/extracted_projection_data/TINV_clim_lininter_GMFD/total_energy/price014pc
file-organize: [ssp, region]
do-montecarlo: no
only-models: all
only-iam: null
column: rebased
output-format: valuescsv
