outputdir: outputs/energy_pixel_interaction/impacts-blueghost/median_OTHERIND_electricity_TINV_clim_GMFD_dm
levels-weighting: population * social/baselines/energy/WITCHGLOBIOM42_rcp85_Prices_COMPILE.dta:country:year:electricitycompile_price
aggregate-weighting-numerator: population * social/baselines/energy/WITCHGLOBIOM42_rcp85_Prices_COMPILE.dta:country:year:electricitycompile_price
aggregate-weighting-denominator: sum-to-1
infix: WITCHGLOBIOM42_rcp85
rcp: rcp85
only-farmers: ['', 'histclim']
