results-root: /shares/gcp/outputs/energy/impacts-blueghost/median_OTHERIND_electricity_TINV_clim_income_spline_GMFD_dm
output-dir: /shares/gcp/social/parameters/energy/extraction/multi-models/rationalized_code/break2_Exclude_all-issues_semi-parametric/TINV_clim_income_spline_GMFD/median_OTHERIND_electricity_TINV_clim_income_spline_GMFD/price03pc
file-organize: [ssp, region]
do-montecarlo: no
only-rcp: null
only-models: all
only-iam: null
deltamethod: true
column: rebased
output-format: valuescsv
