outputdir: outputs/energy/impacts-blueghost/median_OTHERIND_other_energy_TINV_clim_income_spline_GMFD
levels-weighting: population * social/baselines/energy/REMIND17CEMICS_rcp85_Prices_COMPILE.dta:country:year:other_energycompile_price
aggregate-weighting-numerator: population * social/baselines/energy/REMIND17CEMICS_rcp85_Prices_COMPILE.dta:country:year:other_energycompile_price
aggregate-weighting-denominator: sum-to-1
infix: REMIND17CEMICS_rcp85
rcp: rcp85
